<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="ForesTycoon.Engine" />
    <Using Include="ForesTycoon.Ecology" />
    <Using Include="ForesTycoon.TreeModels" />
    <Using Include="ForesTycoon.Rendering" />
    <Using Include="ForesTycoon.Models" />
    <Using Include="ForesTycoon.Effects" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForesTycoon\ForesTycoon.csproj" />
    <ProjectReference Include="..\ForesTycoon.Engine\ForesTycoon.Engine.csproj" />
    <ProjectReference Include="..\ForesTycoon.Ecology\ForesTycoon.Ecology.csproj" />
    <ProjectReference Include="..\ForesTycoon.TreeModels\ForesTycoon.TreeModels.csproj" />
    <ProjectReference Include="..\ForesTycoon.Rendering\ForesTycoon.Rendering.csproj" />
    <ProjectReference Include="..\ForesTycoon.Models\ForesTycoon.Models.csproj" />
    <ProjectReference Include="..\ForesTycoon.Effects\ForesTycoon.Effects.csproj" />
  </ItemGroup>

</Project>
